[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_BASE = "https://universitet-backend.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_BASE = "https://universitet-backend.onrender.com/api"